services:
  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: mentalspace-backend
    environment:
      NODE_ENV: production
      DATABASE_URL: 
      JWT_SECRET: 
      JWT_EXPIRES_IN: 
      PORT: 7000
      DB_HOST: database-1-instance-1.cny40qqomphs.us-east-2.rds.amazonaws.com
      DB_PORT: 5432
    ports:
      - "7000:7000"
    networks:
      - mentalspace-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: mentalspace-frontend
    environment:
      VITE_API_URL: http://backend:7000
    # Frontend port handled by nginx
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - mentalspace-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy
  # nginx:
  #   image: nginx:alpine
  #   container_name: mentalspace-nginx
  #   ports:
  #     - "443:443"
  #     - "3000:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf

  #   depends_on:
  #     - frontend
  #     - backend
  #   networks:
  #     - mentalspace-network

networks:
  mentalspace-network:
    driver: bridge
