project_id = "wjaccopklttdvnutdmtu"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[realtime]
enabled = true
ip_version = "ipv4"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
api_port = 54325
admin_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"
s3_protocol = "http"

[auth]
enabled = true
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[functions.rate-limiter]
verify_jwt = false

[functions.api-logger]
verify_jwt = false

[functions.backup-manager]
verify_jwt = false

[functions.security-monitor]
verify_jwt = false

[edge-runtime]
enabled = true
ip_version = "ipv4"