name: Deploy to Linux EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci

  deploy:
    needs: test
    runs-on: self-hosted  # This runs on YOUR Linux Server
    if: github.ref == 'refs/heads/main'
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      VITE_API_TIMEOUT: ${{ secrets.VITE_API_TIMEOUT }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Deploy to Linux Server
      run: |
        echo "Starting deployment..."
        set -x  # Enable debug mode to show all commands
        
        cd /home/ec2-user/mentalspace-ehr
        
        # Check if directory exists and is a git repository
        if [ ! -d ".git" ]; then
          echo "Git repository not found. Cleaning directory and cloning from GitHub..."
          rm -rf /home/ec2-user/mentalspace-ehr/*
          rm -rf /home/ec2-user/mentalspace-ehr/.* 2>/dev/null || true
          git clone https://github.com/Yi-Jacob/mentalspace-ehr.git .
        else
          echo "Git repository found. Pulling latest changes..."
          git pull origin main
        fi
        
        # Create frontend .env file (no secrets)
        echo "Creating frontend .env file..."
        echo "VITE_API_URL=http://3.17.184.2:7000" > apps/frontend/.env
        echo "VITE_API_TIMEOUT=${VITE_API_TIMEOUT}" >> apps/frontend/.env
        chmod 600 apps/frontend/.env
        
        # Create backend .env file (with secrets)
        echo "Creating backend .env file..."
        echo "NODE_ENV=production" > apps/backend/.env
        echo "DATABASE_URL=${DATABASE_URL}" >> apps/backend/.env
        echo "JWT_SECRET=${JWT_SECRET}" >> apps/backend/.env
        echo "OPENAI_API_KEY=${OPENAI_API_KEY}" >> apps/backend/.env
        echo "JWT_EXPIRES_IN=24h" >> apps/backend/.env
        echo "PORT=7000" >> apps/backend/.env
        chmod 600 apps/backend/.env
        
        echo "Stopping existing containers..."
        docker-compose down --remove-orphans
        
        echo "Building and starting containers..."
        docker-compose up -d --build
        
        echo "Waiting for containers to start..."
        sleep 30
        
        echo "Checking container status..."
        docker ps -a
        
        echo "Checking backend logs (last 100 lines)..."
        docker logs mentalspace-backend --tail=100 || echo "Backend container not found"
        
        echo "Checking backend exit code..."
        docker inspect mentalspace-backend --format='{{.State.ExitCode}}' || echo "Container not found"
        
        echo "Checking all container logs..."
        docker-compose logs --tail=100
        
        echo "Checking backend .env file content (non-sensitive)..."
        echo "Backend .env file exists: $(test -f apps/backend/.env && echo 'YES' || echo 'NO')"
        echo "Backend .env file size: $(wc -c < apps/backend/.env) bytes"
        
        echo "Deployment completed!" 
