name: Deploy to Windows EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci

  deploy:
    needs: test
    runs-on: self-hosted  # This runs on YOUR Windows Server
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Deploy to Windows Server
      run: |
        Write-Host "Starting deployment..." -ForegroundColor Green
        Set-Location "C:\mentalspace-ehr"
        git pull origin main
        docker-compose down
        docker-compose up -d --build
        Write-Host "Deployment completed!" -ForegroundColor Green 